dataset:
  dataset_name: mit_movie
  task_name: trivia
  dataset_dir: ~/itrain/itrain/ext/datasets/mit_movie.py
model:
  model_name_or_path: roberta-base
  use_fast_tokenizer: true
  train_adapter: true
  adapter_config: pfeiffer
training:
  learning_rate: 0.0001
  batch_size: 32
  num_train_epochs: 15
  patience: 4
  patience_metric: eval_accuracy
evaluation: test
logging:
  wandb:
    project: itrain-experiments
restarts: 3
