dataset:
  dataset_name: quail
  max_seq_length: 384
model:
  model_name_or_path: roberta-base
  use_fast_tokenizer: false
  train_adapter: true
  adapter_config: pfeiffer
training:
  learning_rate: 0.0001
  batch_size: 4
  num_train_epochs: 15
  patience: 4
  patience_metric: eval_accuracy
evaluation: true
logging:
  wandb:
    project: itrain-experiments
restarts: 3
